#!/usr/bin/env sh

# shellcheck disable=SC1091
. "$HOME/.config/xorg/xprofile"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
        done
    unset f
fi

WM=bspwm

while true; do
    date >> ~/.local/share/$WM.log
    $WM 2>> ~/.local/share/$WM.log
done
