#!/usr/bin/env sh

# Keyboard
kbset &

# Appearance
setbg &
xrdb ~/.config/xorg/Xresources
xsetroot -cursor_name left_ptr
picom -b --experimental-backends &
redshift &
unclutter --timeout 3 &

# Daemons
sxhkd &
dunst &
bard init >> "$XDG_CACHE_HOME/bard.log" 2>&1 &
syncthing --no-browser &
mpd && mpdnot &
batwatch &

# Pings
rssping &
forecast &
