#!/bin/sh

# Background
setbg &

# Keyboard
kbset &

# Xresources
xrdb ~/.config/xorg/Xresources.custom 2>/dev/null || xrdb ~/.config/xorg/Xresources

# Start up daemons
sxhkd &
dunst &
xcompmgr &
syncthing -no-browser >/dev/null &
unclutter --timeout 3 &
mpd &
