window:
  padding:
    x: 10
    y: 10
  dynamic_padding: true
  opacity: 0.7

font:
  size: 10

colors:
  primary:
    background: "#131313"
    foreground: "#ebdbb2"

  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#a89984"

  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"

  transparent_background_colors: true

selection:
  save_to_clipboard: true

key_bindings:
  - { key: V, mods: Alt, action: Paste }
  - { key: C, mods: Alt, action: Copy }
  - { key: Insert, mods: Shift, action: PasteSelection }
  - { key: K, mods: Alt|Shift, action: IncreaseFontSize }
  - { key: J, mods: Alt|Shift, action: DecreaseFontSize }
  - { key: K, mods: Alt, action: ScrollLineUp }
  - { key: J, mods: Alt, action: ScrollLineDown }
  - { key: U, mods: Alt, action: ScrollPageUp }
  - { key: D, mods: Alt, action: ScrollPageDown }
  - { key: Slash, mods: Alt, action: SearchForward }
  - { key: Slash, mods: Alt|Shift, action: SearchBackward }
  - { key: G, mods: Alt, action: ScrollToTop }
  - { key: G, mods: Alt|Shift, action: ScrollToBottom }

hints:
  alphabet: "jfkdls;ahgurieowpq"
  enabled:
    - regex:
        "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
        [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      mouse:
        enabled: true
        mods: None
      binding:
        key: O
        mods: Alt
    - regex:
        "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
        [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      action: Copy
      post_processing: true
      mouse:
        enabled: true
        mods: None
      binding:
        key: Y
        mods: Alt
