[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mods = "Alt|Shift"

[colors]
transparent_background_colors = true

[colors.primary]
background = "#131313"
foreground = "#ebdbb2"

[colors.normal]
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"

[font]
size = 16

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "O"
mods = "Alt"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Copy"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "Y"
mods = "Alt"

[hints.enabled.mouse]
enabled = true
mods = "None"

[cursor.style]
blinking = "Never"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
opacity = 0.7

[window.padding]
x = 5
y = 5

[keyboard]
