#!/usr/bin/env sh

mkshortcuts

# shellcheck source=/dev/null
{
    . ~/.config/shell/shortcutrc
    . ~/.config/shell/aliasrc
    . ~/.config/shell/aesthrc
    if [ -f ~/.config/shell/privaterc ]; then
        . ~/.config/shell/privaterc
    fi
}
