#!/usr/bin/env sh

while getopts b o; do
    case "$o" in
        b) BASE64=1 ;;
        *) exit 1 ;;
    esac
done

shift $((OPTIND - 1))

file="$(basename "$QUTE_URL")"
ext="${file##*.}"
dir="$(echo "${1:?}" | sed "s:^~:$HOME:")"

if [ -n "$BASE64" ]; then
    outfile="$dir/$(echo "$QUTE_URL" | base64 -w 10 | head -n 1).$ext"
else
    outfile="$dir/$file"
fi

set -e
mkdir -p "$dir"
curl "$QUTE_URL" -o "$outfile"

echo "$outfile"
