#!/usr/bin/env sh

while getopts b o; do
    case "$o" in
        b) BASE64=1 ;;
        *) exit 1 ;;
    esac
done

shift $((OPTIND - 1))

cd "$HOME/dl" || exit 1

file="$(basename "$QUTE_URL")"
dir="$(echo "${1:-$HOME/dl}" | sed "s:^~:$HOME:")"

echo "dl: downloading $QUTE_URL"
curl -LO "$QUTE_URL"

if [ -n "$BASE64" ]; then
    store "$HOME/dl/$file" "$dir"
else
    mv "$file" "$dir"
fi
