#!/bin/sh

# Background
setbg &

# Keyboard
setxkbmap -option caps:escape -option compose:sclk -variant nodeadkeys se
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 300 50 &

# Xresources
xrdb ~/.Xresources

# Start up daemons
sxhkd &
dunst &
xcompmgr &
syncthing -no-browser >/dev/null &
unclutter --timeout 3 &
mpd &
