#!/usr/bin/env sh

BAR_PADDING=25

###

bspc rule -r "*"

mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

if ! echo "$mainmonitor" | grep LVDS > /dev/null 2>&1; then
       xrandr --output "$mainmonitor" --auto --output LVDS1 --off
fi

bspc monitor "$mainmonitor" -d 1 2 3 4 5 6 7 8 9 0

bspc config focus_follows_pointer true

# aesthics
bspc config bottom_padding $BAR_PADDING
bspc config border_width 2
bspc config focused_border_color '#d79921'
bspc config window_gap 30
bspc config honor_size_hints true

# No border if one window
bspc config single_monocle true
bspc config borderless_monocle true

# dwm-like behavior
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc rule -a '*:*' node=@/1

# Per program rules
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled

killall dzen2
pgrep -f 'bspwm/bar.py' | xargs kill

xdpyinfo \
    | grep dimensions \
    | awk '{print $2}' \
    | awk -Fx '{print $1, $2}' \
    | {
        read -r _ h
        python ~/.config/bspwm/bar.py \
            | SHELL=/bin/sh dzen2 \
                -y "$h" -fg '#ffeeee' -bg '#111111' -ta left -h $BAR_PADDING
    } &

wait
