#!/usr/bin/env sh

BAR_PADDING=25

monitors() {
    xrandr -q | rg '\bconnected\b' | cut -d' ' -f1
    # bspc query --monitors --names
}

## reset

# bspc query --monitors --names | while read -r mon; do
#     bspc monitor "$mon" -r
# done

bspc rule -r "*"

## setup

monitors | while read -r mon; do
    xrandr --output "$mon" --auto --output LVDS1 --off
    bspc monitor "$mon" -d 1 2 3 4 5 6 7 8 9 0
done

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

# aesthics
bspc config top_padding $BAR_PADDING
bspc config bottom_padding $BAR_PADDING
bspc config border_width 2
bspc config focused_border_color '#d79921'
bspc config window_gap 40
bspc config honor_size_hints true

# No border if one window
bspc config single_monocle true
bspc config borderless_monocle true

# dwm-like tiling
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc rule -a '*:*' node=@/1

# Per program rules
bspc rule -a Zathura state=tiled
bspc rule -a '*:fugi' state=tiled
bspc rule -a FloatTerm state=floating

killall polybar
monitors | while read -r mon; do
    MONITOR=$mon polybar -r top >/dev/null 2>&1 &
    MONITOR=$mon polybar -r bottom >/dev/null 2>&1 &
done

wait
