#!/usr/bin/env sh

bspc rule -r "*"

mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

if ! echo "$mainmonitor" | grep LVDS >/dev/null 2>&1; then
	xrandr --output "$mainmonitor" --auto --output LVDS1 --off
fi

bspc monitor $mainmonitor -d 1 2 3 4 5 6 7 8 9 0

# bspc config focus_follows_pointer true

# aesthics
bspc config border_width 2
bspc config focused_border_color '#d79921'
bspc config window_gap 30
bspc config honor_size_hints true

# No border if one window
bspc config single_monocle true
bspc config borderless_monocle true

# dwm-like behavior
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc rule -a *:* node=@/1

# Per program rules
bspc rule -a Zathura state=tiled

# Start polybar
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep .1; done
for i in $( polybar -m | awk -F: '{print $1}' ); do
	MONITOR=$i polybar default 2>/home/nico/.local/share/polybar.log &
done

# bspswallow
pgrep bspswallow || bspswallow &
