# Source rcfiles
{
	shortcuts
	source "$HOME/.config/rcfiles/shortcutrc"
	source "$HOME/.config/rcfiles/aliasrc"
	source "$HOME/.config/rcfiles/colorrc"
} >/dev/null

#export PS1="\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 11)\]\w\[$(tput setaf 1)\]]\[$(tput setaf 15)\]\\$ \[$(tput sgr0)\]"
export PS1=" \[$(tput bold)$(tput setaf 4)\]\w \[$(tput setaf 15)\]\\$ \[$(tput sgr0)\]"

# Some misc settings
stty -ixon
HISTSIZE=""
HISTFILESIZE=""
