#!/bin/sh
# Profile file. Runs on login.

export PATH="$HOME/.local/bin:$PATH"
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export READER="zathura"
export FILE="lf"

export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export INPUTRC="$HOME/.config/inputrc"
export LESSHIST="-"

export LOCATION="Ljungsbro"
export HOMEPAGE="$HOME/repos/homepage/home.html"
export GIT="https://github.com/yettinmoor"

source "$HOME/.$( basename "$0" )rc"

# Autorun startx
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Xorg >/dev/null && exec startx

# Switch escape and caps if tty:
sudo -n loadkeys ~/.local/share/ttymaps.kmap 2>/dev/null
