#!/bin/sh

# Background
setbg &

# Keyboard
setxkbmap -option caps:escape -option compose:sclk -variant nodeadkeys se
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 300 50 &

# Xresources
xrdb ~/.Xresources

# Start up daemons
sxhkd &
dunst &
xcompmgr &
syncthing -no-browser >/dev/null &
unclutter --timeout 3 &
mpd &

# dwmbar
dwmbar init
rssping &
forecast &
while pgrep -x mpd; do
	mpc idle >/dev/null 2>&1
	dwmbar music
done &

# dwm
while true; do
	dwm 2>> ~/.local/share/dwm.log
done
