#!/bin/sh

# Background
setbg &

# Keyboard
setxkbmap -option caps:super se && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 300 50 &

# Xresources
xrdb ~/.Xresources

# Start up daemons
sxhkd &
unclutter &
dunst &
xcompmgr &
#syncthing -no-browser >/dev/null &
unclutter --timeout 3 &
mpd &

# Misc stuff
rssping &
forecast $LOCATION &
pulsemixer --set-volume 50 &

# dwmbar
dwmbar init &
while pgrep -x mpd; do
	mpc idle >/dev/null 2>&1
	dwnbar music
done &

# dwm
while true; do
	dwm 2> ~/.local/share/dwm.log
done
