#!/bin/sh

filter() {
	sed "/^volume:/d" | tac | sed -e "s/\\&/&amp;/g;s/\\[paused\\].*/<span color=\"#aaaaaa\">/g;s/\\[playing\\].*/<span>/g" | tr -d '\n' | sed -e "s/$/<\\/span>/g"
}

case $BLOCK_BUTTON in
	1) mpc toggle | filter ;;
	*) mpc -f "%title%" | filter ;;
esac
