#!/bin/sh
# Displays torrent info in i3bar

case $BLOCK_BUTTON in
    1) $TERMINAL -e tremc;;
esac

transmission-remote -l | grep % |
	sed " # This first sed command is to ensure a desirable order with sort
		s/.*100%.*/N/;
		s/.*Stopped.*/A/;
		s/.*Idle.*/A/;
		s/.*Uploading.*/L/;
		s/.*Seeding.*/L/;
		s/.*%.*/M/" | sort -h | uniq -c |
			sed " # Now we replace the standin letters with icons.
				s/A/~/;
				s/L/^/;
				s/M/+/;
				s/N/!/" | awk '{print $2 $1}' | tr '\n' ' ' | sed -e "s/ $//g"
