#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e pulsemixer & ;;
	2) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "Muted" && exit

#printf "Vol %s%%" "$(pulsemixer --get-volume | awk '{print $1}')"
printf "%s" "$( pulsemixer --get-volume | awk '{print $1}' | volume_draw.c )"
