#!/bin/sh

# Programs
alias f="\$FILE"
alias v="\$EDITOR"
alias magit="\$EDITOR -c MagitOnly"
alias x="sxiv -at * 2>/dev/null & disown"
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc\$( date +%s )"
alias ffmpeg="ffmpeg -hide_banner"
alias trem="transmission-remote"
alias cal="calcurse -D ~/.config/calcurse"
alias pw="pass -c"
alias tw="ccwrapper"

# General shortcuts
alias mkd="mkdir -v"
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi --force"
alias ka="killall"
alias p="sudo pacman"
alias SS="sudo systemctl"
alias upc="sudo pacman -Syu; dwmbar packages"
alias wttr="less -S /tmp/weatherreport"

# YouTube
alias ytd="youtube-dl --add-metadata -i -f \"bestvideo[height<=1080]+bestaudio/best\" -o '%(upload_date)s - %(title)s.%(ext)s'"
alias ytda="ytd -x -f \"bestaudio[ext=mp3]/best\""
alias ytv="youtube-viewer -C"

# Neovim
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# fzf
se() { fd -t f -L . ~/.local ~/.config | fzf --reverse --color=16 | xargs -r "$EDITOR"; }
vf() { fzf --reverse --color=16 | xargs -r "$EDITOR"; }
mo() { mv "${@?}" "$( cut -f2- ~/.config/directories | fzf | sed "s:~:$HOME:" )"; }
co() { cp "${@?}" "$( cut -f2- ~/.config/directories | fzf | sed "s:~:$HOME:" )"; }

# Convenience functions
src()  { . "$HOME/.profile"; echo "Reloaded bashrc, profile and shortcuts."; }
kr()   { killall "$1"; setsid "$1" >/dev/null 2>&1 & echo "Killed and revived $1"; }
xw()   { xwininfo -tree -root | grep "${1:-""}"; }

foo()  { echo "Hello world!"; }
