#!/usr/bin/env sh
# Profile file. Runs on login.

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:=$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:=$HOME/.local/share}

export SHELL=zsh
export PATH=$HOME/.local/bin:$(go env GOBIN):$HOME/.nimble/bin:$HOME/.ghcup/bin:$HOME/.cabal/bin:$PATH
export EDITOR=nvim
export TERMINAL=st
export BROWSER=brave
export READER=zathura
export FILE=lf
export ZDOTDIR=$HOME/.config/zsh

export SUDO_ASKPASS=$HOME/.local/bin/dmenupass
export INPUTRC=$HOME/.config/inputrc
export LESSHISTFILE=/dev/null
export XAUTHORITY=$HOME/.config/xorg/.Xauthority
export PYTHONHISTORY=$XDG_CACHE_HOME/python

export HOMEPAGE=$HOME/.local/share/splash/index.html
export GIT=git@github.com:yettinmoor

export MAKEFLAGS="-j $(grep -c ^processor /proc/cpuinfo)"

export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export XIM_PROGRAM=/usr/bin/ibus-daemon
export QT_QPA_PLATFORMTHEME=qt5ct

export LD_LIBARY_PATH=/usr/local/lib

export GPG_TTY=$(tty)

export DOTNET_CLI_TELEMETRY_OPTOUT=1

source $HOME/.config/zsh/.zshrc

# Autorun startx
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Xorg >/dev/null && exec startx

# Switch escape and caps if tty:
sudo -n loadkeys ~/.local/share/ttymaps.kmap 2>/dev/null
