#!/usr/bin/env bash
# Thanks to Derek Taylor for this script
readonly ID_PREVIEW="preview"

#AUTO_REMOVE="yes"
# By enabling this option the script will remove the preview file after it is drawn
# and by doing so the preview will always be up-to-date with the file.
# This however, requires more CPU and therefore affects the overall performance.

if [ -e "$FIFO_UEBERZUG" ]; then
	if [[ "$1" == "draw" ]]; then
		declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
							[x]="$2" [y]="$3" [width]="$4" [height]="$5" \
							[path]="${PWD}/$6") \
			> "$FIFO_UEBERZUG"

	elif [[ "$1" == "videopreview" ]]; then
		echo -e "Loading preview..\nFile: $6"
		[[ ! -d "/tmp${PWD}/$6/" ]] && mkdir -p "/tmp${PWD}/$6/"
		[[ ! -f "/tmp${PWD}/$6.png" ]] && ffmpegthumbnailer -i "${PWD}/$6" -o "/tmp${PWD}/$6.png" -s 0 -q 10
		declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
							[x]="$2" [y]="$3" [width]="$4" [height]="$5" \
							[path]="/tmp${PWD}/$6.png") \
			> "$FIFO_UEBERZUG"

	elif [[ "$1" == "docpreview" ]]; then
		echo -e "\n Loading..."
		[[ ! -d "/tmp${PWD}" ]] && mkdir -p "/tmp${PWD}"
		case "$6" in
			*pdf) com="pdftoppm -png -singlefile" ;;
			*djvu) com="ddjvu -format=pnm -page=1" && ext=".png" ;;
			*) exit 1 ;;
		esac
		[[ ! -f "/tmp${PWD}/$6.png" ]] && $com "$6" "/tmp${PWD}/$6$ext" >/dev/null 2>&1
		declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
							[x]="$2" [y]="$3" [width]="$4" [height]="$5" \
							[path]="/tmp${PWD}/$6.png") \
			> "$FIFO_UEBERZUG"

	elif [[ "$1" == "clear" ]]; then
		declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") \
			> "$FIFO_UEBERZUG"
		[[ ! -z $AUTO_REMOVE ]] && [[ -f "/tmp${PWD}/$6.png" ]] && rm -f "/tmp${PWD}/$6.png"
		[[ ! -z $AUTO_REMOVE ]] && [[ -d "/tmp${PWD}/$6/" ]] && rm -rf "/tmp${PWD}/$6/"

	fi
fi
