#!/bin/sh
# Volume interface for sxhkd. Updates dwmbar and notifies with dunst.

unmute() {
	amixer -M scontrols | cut -d \' -f 2 | xargs -I % amixer -M sset % unmute >/dev/null 2>&1
}

case "$1" in
	vol)
		amixer -M sset Master $2
		amixer -M get Master | grep -q "off" && unmute ;;
	mute)
		if amixer -M get Master | grep -q "off"; then
			unmute
		else
			amixer -M sset Master mute
		fi ;;
esac

dwmbar volume

amixer -M get Master | grep -q "off" \
	&& dunstify -u low -r 54321 "Muted" \
	|| dunstify -u low -r 54321 "Volume: $( amixer -M get Master | grep -o "[0-9]*%" )"
