#!/usr/bin/env sh
# Volume interface for sxhkd.

if amixer get Master | grep -q "\\[on\\]"; then
	amixer -M sset Master $1
	dunstify -u low -r 54321 "Volume: $( amixer -M get Master | grep -o "[0-9]*%" )"
else
	amixer scontrols | cut -d \' -f 2 | xargs -I % amixer sset % unmute >/dev/null 2>&1
	dunstify -u low -r 54321 "Muted"
fi
