#!/bin/sh
# Volume interface for sxhkd. Updates dwmbar and notifies with dunst.

amixer get Master | grep -q "\\[on\\]" \
	&& amixer -M sset Master $1 \
	|| amixer scontrols | cut -d \' -f 2 | xargs -I % amixer sset % unmute >/dev/null 2>&1

dwmbar volume

amixer get Master | grep -q "off" \
	&& dunstify -u low -r 54321 "Muted" \
	|| dunstify -u low -r 54321 "Volume: $( amixer -M get Master | grep -o "[0-9]*%" )"
