#!/usr/bin/env sh
# Moves photos from synced phone to repos for later filtering.

[ -d ~/phone ] || exit 1
[ -d ~/repos/phone ] || mkdir -p ~/repos/phone

cd ~/phone || exit 1
fd --exclude 'WallPaper' '(jp?g|png)$' -x sh -c '\
	jhead -autorot {}; \
	mv -vf {} ~/repos/phone' 2>/dev/null

cd ~/repos/phone || exit 1
for f in *; do
	mv "$f" "$( echo $f | sed 's/IMG-//; s/_/-/g' )" 2>/dev/null
done
