#!/usr/bin/env sh

bold=0

if [ $# -gt 0 ]; then
    # print immediately

    [ "$1" = -b ] && {
        bold=1
        shift
    }

    if [ -z "$NO_COLOR" ]; then
        case "$1" in
            blk) printf '\033[%d;30m' "$bold" ;;
            red) printf '\033[%d;31m' "$bold" ;;
            grn) printf '\033[%d;32m' "$bold" ;;
            yel) printf '\033[%d;33m' "$bold" ;;
            blu) printf '\033[%d;34m' "$bold" ;;
            prp) printf '\033[%d;35m' "$bold" ;;
            cyn) printf '\033[%d;36m' "$bold" ;;
            wht) printf '\033[%d;37m' "$bold" ;;
            clr) printf '\033[0m' ;;
            help | -h | --help)
                {
                    echo 'colors: blk, red, grn, yel, blu, prp, cyn, wht'
                    echo 'clear:  clr'
                } >&2
                ;;
        esac
    fi
    shift
    if [ $# -gt 0 ]; then
        printf "%b" "$@"
        color clr
    fi
else
    # export (should be sourced)
    export COLOR_BLK='\033[0;30m'
    export COLOR_RED='\033[0;31m'
    export COLOR_GRN='\033[0;32m'
    export COLOR_YEL='\033[0;33m'
    export COLOR_BLU='\033[0;34m'
    export COLOR_PRP='\033[0;35m'
    export COLOR_CYN='\033[0;36m'
    export COLOR_WHT='\033[0;37m'

    export COLOR_BLK_BOLD='\033[1;30m'
    export COLOR_RED_BOLD='\033[1;31m'
    export COLOR_GRN_BOLD='\033[1;32m'
    export COLOR_YEL_BOLD='\033[1;33m'
    export COLOR_BLU_BOLD='\033[1;34m'
    export COLOR_PRP_BOLD='\033[1;35m'
    export COLOR_CYN_BOLD='\033[1;36m'
    export COLOR_WHT_BOLD='\033[1;37m'

    export COLOR_CLR='\033[0m'
fi
