#!/usr/bin/env sh
# Compiles or runs programs e.g. C, python.
# Formats .tex, groff (.mom, .ms), .rmd, .md into pdf.
# Opens .sent files as sent presentations.
# Runs scripts based on extension or shebang

file="$( readlink -f "$1" )"
dir="$( dirname "$file" )"
base="${file%.*}"

cd "$dir" || exit 1

if ls "Makefile" >/dev/null 2>&1; then
	make
	pwd -P | grep 'repos/bin' && sudo make install
	exit 0
fi

case "$file" in
	# Programming
	*\.c)   gcc -std=c99 -Wall -g -o "$base" "$file" ;;
	*\.py)  python "$file" ;;
	*\.scm) csi    "$file" ;;
	*\.cs)  mcs    "$file" ;;

	# Document formatting
	*\.tex) xelatex --output-directory="$dir" "$base" ;;
	*\.md)  pandoc "$file" --pdf-engine=xelatex -o "$base".pdf ;;

	# Shebang
	*) sed -n '1{/^#!/s///p}' "$file" | xargs -r -I % "$file" ;;
esac
