#!/bin/sh
# Compiles or runs programs e.g. C, python.
# Formats .tex, groff (.mom, .ms), .rmd, .md into pdf.
# Opens .sent files as sent presentations.
# Runs scripts based on extension or shebang

file=$( readlink -f "$1" )
dir=$( dirname "$file" )
base="${file%.*}"

cd "$dir" || exit

textype() { \
	xelatex --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" &&
	xelatex --output-directory="$dir" "$base" &&
	xelatex --output-directory="$dir" "$base"
	}

case "$file" in
	# Make install
	*config\.h) sudo make install ;;

	# Programming
	*\.c)  ccwrapper "$file" ;;
	*\.py) python "$file" ;;
	*\.go) go run "$file" ;;

	# Document formatting
	*\.tex) textype "$file" ;;
	*\.ms)  refer -PS -e "$file" | groff -me -ms -kejpt -T pdf > "$base".pdf ;;
	*\.mom) refer -PS -e "$file" | groff -mom -kejpt -T pdf > "$base".pdf ;;
	*\.md)  pandoc "$file" --pdf-engine=xelatex -o "$base".pdf ;;

	# Sent
	*\.sent) setsid sent "$file" 2>/dev/null & ;;

	# Shebang
	*) sed 1q "$file" | grep "^#!/" | sed "s/^#!//" | xargs -r -I % "$file" ;;
esac
