#!/usr/bin/env sh
# Gives a dmenu prompt to mount unmounted drives.
# If they're in /etc/fstab, they'll be mounted automatically.
# Otherwise, you'll be prompted to give a mountpoint from already existsing directories.
# If you input a novel directory, it will prompt you to create that directory.

getmount() {
	[ -z "$chosen" ] && exit 1
	mp="$( find $1 2>/dev/null | dmenu -i -p "Type in mount point." )" || exit 1
	[ ! -d "$mp" ] && prompt "$mp does not exist. Create it?" "(mkdir -p "$mp" || sudo -A mkdir -p "$mp")"
}

mountusb() {
	chosen="$( echo "$usbdrives" | dmenu -i -p "Mount which drive?" | cut -d ' ' -f 1 )"
	sudo -A mount "$chosen" 2>/dev/null && notify-send "💻 USB mounting" "$chosen mounted." && exit 0
	alreadymounted="$( lsblk -nrp | awk '$6=="part"&&$7!~/\/boot|\/home$|SWAP/&&length($7)>1{printf "-not \\( -path *%s -prune \\) \\ \n",$7}' )"
	getmount "/mnt /media /mount /home /usb -maxdepth 5 -type d $alreadymounted"
	case "$( lsblk -no "fstype" "$chosen" )" in
		"vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
		*)      sudo -A mount "$chosen" "$mp"; sudo -A chown "$( whoami )":"$( groups | cut -d ' ' -f 1 )" "$mp";;
	esac
	notify-send "💻 USB mounting" "$chosen mounted to $mp."
}

mountandroid() {
	chosen=$( echo "$anddrives" | dmenu -i -p "Which Android device?" | cut -d : -f 1 )
	getmount "$HOME -maxdepth 3 -type d"
	simple-mtpfs --device "$chosen" "$mp"
	notify-send "🤖 Android Mounting" "Android device mounted to $mp."
}

asktype() {
	"mount$(printf "USB\\nAndroid" | dmenu -i -p "Mount a USB drive or Android device?" | tr '[:upper:]' '[:lower:]')"
}

anddrives="$( simple-mtpfs -l 2>/dev/null )"
usbdrives="$( lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}' )"

[ -z "$usbdrives" ] && [ -z "$anddrives" ] && exit 1

if [ -n "$usbdrives" ]; then
	if [ -n "$anddrives" ]; then
		asktype
	else
		mountusb;
	fi
else
	mountandroid
fi
