#!/usr/bin/env sh

DOT=$HOME/repos/dotfiles

cd $DOT || exit 1

if [ -z "$1" ]; then
    sel() { sort | uniq | fzf --preview="bat -p --color always $DOT/{}"; }
else
    sel() { grep -m 1 "$1"; }
fi

git -C $DOT ls-tree -r --name-only HEAD |
    sel "$1" |
    xargs -r -I {} "$EDITOR" "$DOT/{}"

cd - >/dev/null
