#!/bin/sh
# dwm statusbar script, somewhat inspired by i3blocks.
# Declare a function starting with "get_" to add a block.
# Call "color [dwm statuscolor code]" to color the block.
# Call dwmbar init to set everything up and dwmbar [function name] to update that function.
# E.g. "dwmbar rss" will update the RSS block WITHOUT calling all other functions, like the slow pacman -Qu command.
#
# TODO: add more convenient coloring if I can figure out dwm pango

sep="  |  "
rp="   " # right padding

alias color="echo -n"

get_music() {
	color 
	mpc -f "%artist% - %title%" | sed "/^volume/d" | tac | sed "s/\\[\(.*\)\\].*/\1 /; s/paused/⏸/; s/playing/▶/;"
}

get_timer() {
	ls /tmp/timer* >/dev/null 2>&1 || return 1
	awk -F ';' '{printf "%s %02d:%02d :: ", $1, ($2-'"$( date +%s )"')/60, ($2-'"$( date +%s )"')%60}' /tmp/timer* | sed "s/[^0-9]*$//"
}

get_weather() {
	sed '13q;d' /tmp/weatherreport | \
		grep -o "m\\([+-]\\)*[0-9]\\+" | \
		sort -n -t 'm' -k 2n | \
		sed -n '1p;$p' | \
		tr '\n|m|+' ' ' | \
		awk '{print "" $2 "° " $1 "°"}'
}

get_torrents() {
	color 
	{ transmission-remote -l 2>/dev/null || return 1; } | sed '1d;$d' | \
		sed -E "
			s/.*(100%|Seeding).*/@/;
			s/.*%.*/v/;
			s/.*(Paused|Waiting).*/\./" | \
				sort | uniq -c | awk '{print $2 $1}' | tr '\n' ' ' | sed "s/ $//"
}

get_packages() {
	pacman -Qu | grep -cv "ignored" | sed "/^0/d; s/^[0-9]/? &/"
}

get_rss() {
	color 
	[ -s /tmp/newsupdate ] \
		&& cat /tmp/newsupdate \
		|| newsboat -x print-unread | cut -d' ' -f1 | sed "/^0/d; s/^[0-9]/\! &/"
}

get_volume() {
	amixer -M get Master | grep % | sed 's/.*off.*/Muted/; s/.*\[\([0-9]*\%\)\].*/\1/'
}

get_date() {
	color 
	date '+%a %b/%d (%V)'
}

get_time() {
	date +%R
}

case "$1" in
	init)
		rm -f /tmp/dwmbar
		grep -o "^get_[a-z]*" "$0" | while read f; do
			echo "${f#get_}:$( $f | tr -d '\n' )" >> /tmp/dwmbar
		done ;;
	*)
		command -v "get_$1" >/dev/null 2>&1 || exit 1
		printf ",s/^$1:.*/$1:$( get_$1 | sed 's:/:\\/:g; s:%:%%:g' | tr -d '\n' )/\nwq\n" | ed /tmp/dwmbar >/dev/null ;;
esac

xsetroot -name "$( sed "s/^[a-z]*://; /^.\?$/d; 1,$ a$sep" /tmp/dwmbar | tr -d '\n' | sed "s/$sep$/$rp/" )"
