#!/bin/sh

sep="  :  "
rp="  " # right padding

set_status() {
	# Music
	mpc -f "%artist% - %title%" | sed "/^volume/d" | tac |
		sed "
			s/\\[\(.*\)\\].*/\1 /;
			s/paused/⏸/;
			s/playing/▶/;" | tr -d '\n' | sed -E "s/.+/&${sep}/"

	# Weather
	sed '13q;d' /tmp/weatherreport | \
		grep -o "m\\([+-]\\)*[0-9]\\+" | \
		sort -n -t 'm' -k 2n | \
		sed -n '1p;$p' | \
		tr '\n|m|+' ' ' | \
		awk '{print "" $2 "° " $1 "°"}' | printf "%s${sep}" "$( cat - )"

	# RSS
	[ -s /tmp/newsupdate ] && printf "%s${sep}" "$( cat /tmp/newsupdate | tr -d '\n' )"
	newsboat -x print-unread | cut -d' ' -f1 | sed "/^0/d; s/^[0-9]/! &${sep}/"

	# Volume
	printf "%s%%${sep}" $( pulsemixer --get-volume | cut -d' ' -f1 )

	# Date
	printf "%s" "$( date '+%a %b/%d %R' )"
}

while true; do
	xsetroot -name "$( set_status )$rp"
	sleep 10
done
