#!/usr/bin/env sh
# dwm statusbar script, somewhat inspired by i3blocks.

sep=' / '

get_music() {
	mpc | sed '/^volume/d; 2{s/^\[pa.*/⏸ /; s/^\[pl.*/▶ /}' | tac | tr -d '\n'
}

get_timer() {
	awk -F ';' '{printf "%s %02d:%02d :: ", $1, ($2-'"$( date +%s )"')/60, ($2-'"$( date +%s )"')%60}' /tmp/timer* 2>/dev/null | sed "s/[^0-9]*$//"
}

#get_weather() {
	#{ sed '13q;d' /tmp/weatherreport 2>/dev/null || return 1; } | \
		#grep -oE 'm(e+-])*[0-9]+' | sort -n -t 'm' -k 2n | sed -n '2,${$!d}; s/$/°/p' | tr '\n|m|+' ' ' | \
		#awk '{print "3" $2, "4" $1}'
#}

get_torrents() {
	{ transmission-remote -l 2>/dev/null || return 1; } | \
		sed '1d; $d; s/.*\(Stopped\|n\/a\).*/./; s/.*\(100%\|Seeding\).*/@/; s/.*%.*/v/' | \
		sort | uniq -c | awk '{print $2 $1}' | tr '\n' ' ' | sed "s/ $//"
}

get_packages() {
	pacman -Qu | grep -cv "ignored" | sed "/^0/d; s/^[0-9]/? &/"
}

get_rss() {
	cat /tmp/newsupdate 2>/dev/null || newsboat -x print-unread | awk '/^[1-9]/ {print "!" $1}'
}

get_volume() {
	amixer -M get Master | grep -m 1 '%' | sed 's/.*off.*/Muted/; s/.*\[\([0-9]*\%\)\].*/\1/'
}

get_date() {
	#date '+%a, %b %d (%V)'
	kyou
}

get_time() {
	date +%R
}

case "$1" in
	init)
		grep -o "^get_[a-z]*" "$0" | while read -r f; do echo "${f#get_}:$($f)"; done >/tmp/dwmbar ;;
	*)
		command -v "get_$1" >/dev/null || { echo "dwmbar does not have '$1' function."; exit 1; }
		printf "%s\nwq\n" "/^$1:/s/:.*/:$( "get_$1" | sed -E 's/(\/|&)/\\\1/g')/" | ed -s /tmp/dwmbar ;;
esac

xsetroot -name "$( sed -E /tmp/dwmbar -e 's/^[a-z]*://' -e "/^$/!a\\${sep}" | tr -d '\n' | sed "s:$sep$:  :" )"
