#!/usr/bin/env sh
# A general, all-purpose extraction script.
#
# Default behavior: Extract archive into new directory
# Behavior with `-c` option: Extract contents into current directory

if [ "$1" = '-c' ]; then here='true'; shift; fi

for a in "$@"; do
	archive="$( readlink -f "$a" )"
	dir="$( dirname $archive )"
	if [ -z "$here" ]; then mkdir -p "$dir"; cd "$dir" || exit 1; fi

	case "$archive" in
		*.tar.bz2|*.tar.xz|*.tbz2) tar xvjf "$archive" ;;
		*.tar.gz|*.tgz) tar xvzf "$archive" ;;
		*.lzma) unlzma "$archive" ;;
		*.bz2) bunzip2 "$archive" ;;
		*.rar) unrar x -ad "$archive" ;;
		*.gz) gunzip "$archive" ;;
		*.tar) tar xvf "$archive" ;;
		*.zip) unzip "$archive" ;;
		*.Z) uncompress "$archive" ;;
		*.7z) 7z x "$archive" ;;
		*.xz) unxz "$archive" ;;
		*.exe) cabextract "$archive" ;;
		*) printf "extract: '%s' - unknown archive method\\n" "$archive" ;;
	esac
done
