#!/usr/bin/env sh
# Updates weather forecast of $1, or $LOCATION by default

ping -q -c 1 1.1.1.1 >/dev/null || exit 1
report=$( curl -s "wttr.in/${1:-$LOCATION}" )
echo "$report" | grep "Sorry" && exit 1 # Exit if wttr server overload
echo "$report" >/tmp/weatherreport
dwmbar weather
