#!/usr/bin/env sh

engines=$(
    nl -s ' ' -w 1 <<-EOF
🇯🇵 anthy
🇨🇳 pinyin
🇰🇷 hangul
🇬🇷 keyboard-gr
🇷🇺 keyboard-ru-phonetic
🇮🇱 keyboard-il-phonetic
🇵🇸 keyboard-ara-buckwalter
🇮🇳 keyboard-in-hin-kagapa
EOF
)

case "$1" in
toggle)
    case "$(fcitx5-remote)" in
    1)
        fcitx5-remote -t
        ;;
    2)
        fcitx5-remote -T
        ;;
    *) ;;
    esac
    ;;

select)
    echo "$engines" |
        cut -d ' ' -f1-2 |
        dmenu -p 'Keyboard layout' -L "$(echo "$engines" | wc -l)" -width 10 |
        {
            read -r choice
            choice=$(echo "$engines" | grep "${choice:?}")
            engine=$(echo "$choice" | cut -d ' ' -f3)
            fcitx5-remote -s "$engine"
        }
    ;;

config)
    setsid fcitx5-configtool >/dev/null 2>&1 &
    ;;

*)
    echo invalid option
    exit 1
    ;;
esac
