#!/usr/bin/env sh

cmd="$1"

case "$cmd" in
push | pull)
    shift
    ;;
*)
    echo "$(basename "$0") [push|pull] [dir]?"
    exit 1
    ;;
esac

set -x

# check $MATE defined & connected
[ -z "$MATE" ] && {
    echo "\$MATE not defined"
    exit 1
}
isconnected "$MATE" || {
    echo "$MATE not found on network"
    exit 1
}

p="$(realpath "${1:-.}")"

[ $# -ge 1 ] && shift

case "$cmd" in
push) rsync "$@" -avz "$p" "$MATE:$(dirname "$p")" ;;
pull) rsync "$@" "$MATE:$p" -avz "$(dirname "$p")" ;;
esac
