#!/usr/bin/env sh

cd "$WIKI_DIR" || exit 1

file="log-$(basename "$0").md"
touch "$file"

while getopts exun o; do
    case "$o" in
    e)
        $EDITOR "$file"
        exit
        ;;
    x) filter='read' ;;
    u) filter='unread' ;;
    n) count=1 ;;
    *) exit 1 ;;
    esac
done

shift $((OPTIND - 1))

[ -n "$1" ] && year="$1" || year="$(date +%Y)"

cat "$file" |
    sed "0,/^# $year\$/d; /^# $((year - 1))\$/q" |
    # select headers
    rg '^### \[[ x]\]' |
    case "$filter" in
    read) rg '\[x\]' ;;
    unread) rg '\[ \]' ;;
    '') cat - ;;
    esac |
    # remove header & links
    sed 's/^### //g; s/\[\([^]]*\)\]([^)]*)/\1/g' |
    if [ -z "$count" ]; then
        tr -d '_' | tac
    else
        wc -l
    fi
