#!/usr/bin/env sh
# opout: "open output": A general handler for opening a file's intended output.
# I find this useful especially running from vim.

file="$( readlink -f "$1" )"
base="${file%.*}"

cd "$( dirname "$file" )" || exit 1

case "$file" in
	*.tex|*.md|*.rmd|*.ms|*.me|*.mom) setsid "$READER" "$base".pdf >/dev/null 2>&1 & ;;
	*.html) setsid "$BROWSER" --new-window "$base".html >/dev/null 2>&1 & ;;
	*.sent) setsid sent "$file" >/dev/null 2>&1 & ;;
	*) [ -x "$base" ] && "$base" ;;
esac
