#!/usr/bin/env sh

for file in "$@"; do
    case "$(file --mime-type -bL "$file")" in
        image/png)
            magick "$file" "${file%.png}.jpg" && rm "$file"
            ;;
        image/webp)
            magick "$file" "${file%.webp}.jpg" && rm "$file"
            ;;
        *)
            echo "$file: not a png or webp!"
            ;;
    esac
done
