#!/usr/bin/env sh

image() {
    if [ -z "$SSH_CONNECTION" ] &&
        [ -n "$DISPLAY" ] &&
        [ -z "$WAYLAND_DISPLAY" ]; then
        printf '{"action":"add","identifier":"PREVIEW","x":"%s","y":"%s","width":"%s","height":"%s","scaler":"contain","path":"%s"}\n' \
            "$4" "$5" "$(($2 - 1))" "$(($3 - 1))" "$1" >"$FIFO_UEBERZUG"
        exit 1
    else
        chafa "$1" -s "${4}x"
    fi
}

batorcat() {
    file="${1:--}"
    shift
    if command -v bat >/dev/null 2>&1; then
        bat --color=always -p "$file" "$@"
    else
        cat "$file"
    fi
}

CACHE="$XDG_CACHE_HOME/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"

preview-clean

case "$(file --mime-type "$1" -bL)" in
application/epub+zip)
    [ ! -f "$CACHE" ] && gnome-epub-thumbnailer "$1" "$CACHE" -s 1024
    image "$CACHE" "$2" "$3" "$4" "$5"
    ;;
application/pdf)
    [ ! -f "${CACHE}.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
    image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
    ;;
application/x-bittorrent)
    transmission-show "$1"
    ;;
application/x-object)
    nm "$1"
    ;;
application/x-pie-executable)
    {
        echo '<binary file>'
        readelf -h "$1"
    } | batorcat
    ;;
application/gzip | application/x-rar)
    als "$1"
    ;;
application/zip)
    # fucking hell
    if unzip -lqq "$1" | rg -qiv '(jpe?g|png|url|db|/)$'; then
        unzip -lqq "$1"
    else
        [ ! -f "${CACHE}" ] &&
            unzip -lqq "$1" 2>/dev/null |
            rg -i '(jpe?g|png)$' |
                awk -F ' +' '{$1=$2=$3=$4=""; print}' |
                sed 's/^ \+//; s/\(\[\|\]\|\*\)/\\\1/g' |
                sort -n |
                head -n 1 |
                {
                    read -r extract
                    unzip -p "$1" "$extract" >"$CACHE"
                }
        image "${CACHE}" "$2" "$3" "$4" "$5"
    fi
    ;;
audio/*)
    mediainfo "$1" | tabulate -f plain -s :
    ;;
image/vnd.djvu)
    [ ! -f "$CACHE" ] && ddjvu -format=tif -quality=50 -page=1 "$1" "$CACHE"
    image "$CACHE" "$2" "$3" "$4" "$5"
    ;;
image/svg+xml)
    [ ! -f "${CACHE}.png" ] && magick "$1" "$CACHE.png"
    image "${CACHE}.png" "$2" "$3" "$4" "$5"
    ;;
image/*)
    image "$1" "$2" "$3" "$4" "$5"
    ;;
video/*)
    [ ! -f "${CACHE}.jpg" ] && thumbnailer -o "${CACHE}.jpg" "$1"
    image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
    ;;
*)
    batorcat "$1"
    ;;
esac
