#!/usr/bin/env sh
pw=$( fd "\.gpg" "$HOME/.password-store" | sed "s/.*password-store\///; s/\.gpg$//;" | dmenu -p "pass:" ) || exit 1
pass -c "$pw" && msg="Password copied." || msg="Invalid password."
notify-send -u critical "$msg"
