#!/usr/bin/env sh
# Sets the background with xwallpaper.
# If given a file as argument, will set that file as background.
# `setbg pick`   lets me pick from wp dir with sxiv.
# `setbg random` picks a random wallpaper.

WALL="$XDG_CACHE_HOME/wall"

case "$1" in
random) fd . ~/pics/wallpapers | shuf -n 1 ;;
pick) fd . ~/pics/wallpapers | shuf | sxiv -tio | sed 1q ;;
*) readlink -f "$1" ;;
esac | {
    read -r file
    ln -sfT "$file" "$WALL"
}

xwallpaper --zoom "$WALL"
