#!/bin/bash
# Output locations. Unactivated progs should go to /dev/null.
shell_shortcuts="$HOME/.config/zsh/shortcutrc"
lf_shortcuts="$HOME/.config/lf/lfshortcuts"

# Remove, prepare files
printf "# vim: filetype=sh\\nalias " > "$shell_shortcuts"
printf "# vim: filetype=conf\\n" > "$lf_shortcuts"

# Format `directories` in the correct syntax and sent it to all configs.
sed "s/\s*#.*$//; /^\s*$/d" "$HOME/.config/directories" | tee \
	>( awk '{print $1"=\"cd "$2" && ls\" \\"}' >> "$shell_shortcuts" ) \
	| awk '{print "map g" $1, "cd", $2 "\nmap M" $1, "$mv $fx", $2}' >> "$lf_shortcuts"
# Format `files` in the correct syntax and sent it to all configs.
sed "s/\s*#.*$//; /^\s*$/d" "$HOME/.config/files" | tee \
	>( awk '{print $1"=\"$EDITOR "$2"\" \\"}' >> "$shell_shortcuts" ) \
	| awk '{print "map", $1, "shell $EDITOR", $2}' >> "$lf_shortcuts"
