#!/usr/bin/env sh
# Display contents of selection via dunst.

show() {
    clip="$1"
    cl() { timeout .2s xclip -sel "$clip" -o "$@"; }
    if cl -t TARGETS | grep image/png; then
        set -e
        cl -t image/png >/tmp/clipimg
        notify-send "$clip" -i /tmp/clipimg
        rm /tmp/clipimg
    else
        out=$(cl || echo '<img>')
        [ -n "$out" ] && notify-send "$1" "$out"
    fi
}

choice=$(printf 'show\nqr\ndelete\n' | dmenu -p clip -L 3 || exit 1)

case $choice in
show)
    show clip
    show prim
    ;;
qr)
    xclip -sel clip -o | qrencode -s 25 -o /tmp/qrclip.png || exit 1
    sxiv -pb -N 'qrclip' /tmp/qrclip.png
    rm -f /tmp/qrclip.png
    ;;
delete)
    catecho "$@" | xclip -sel c -i
    catecho "$@" | xclip -sel p -i
    ;;
*) exit 1 ;;
esac
