#!/bin/sh
# Display contents of selection via dunst.

clip=$( xclip -sel clip -o )
prim=$( xclip -sel prim -o )

[ -n "$clip" ] && notify-send "Clipboard:" "$clip"
[ -n "$prim" ] && notify-send "Primary:" "$prim"
