#!/usr/bin/env sh
# SLOC counter for code. Doesn't count comments & empty lines. Default comment tag is "#".

count() {
	case "$1" in
		*.c|*.h)	com="\/[\/\*]" ;;
		*.tex)		com="%" ;;
		*)			com="#" ;;
	esac
	grep -cvE "(^\s*$com|^\s*$)" "$1"
}

for f in ${@:-*}; do
	[ -f $f ] || continue
	n=$( count $f )
	out="${out}$f $n\n"
	tot=$((tot+n))
done

[ $( printf "$out" | wc -l ) -gt 1 ] && out="${out}TOTAL $tot"
printf "$out" | column -t -R 2
