#!/usr/bin/env sh

lang="$SCRAPE_LANG"

while getopts xlrL:t:T: opt; do
    case $opt in
    x)
        left=1
        right=1
        ;;
    l) left=1 ;;
    r) right=1 ;;
    L) lang="$OPTARG" ;;
    t) match="$OPTARG" ;;
    T) unmatch="$OPTARG" ;;
    *) exit 1 ;;
    esac
done
shift $((OPTIND - 1))

search="$(catecho "$@")"

[ -n "$left" ] && search="\b${search}"
[ -n "$right" ] && search="${search}\b"

rg -sI "$search.*\t.*$match" "$HOME/lib/lang/res/tatoeba/$lang" |
    if [ -n "$unmatch" ]; then rg -iv "$unmatch"; else cat; fi |
    shuf |
    head -n 50 |
    awk -v FS='\t' '{printf "%s\n%s\n\n", $1, $2}' |
    sed '$d' |
    $PAGER
