#!/bin/sh
# Timer with dmenu and dwmbar integration, bound to mod+F4. Notifies with dunst upon completion.

input="$( dmenu -p "Time:" <&- )" || exit 1
topic="$( dmenu -p "Note:" <&- )" || exit 1

file="/tmp/timer$$"
trap 'rm -f "$file"; dwmbar timer; exit 1' INT TERM

start="$( date +%s )"

case "$input" in
	*:*) end=$( date -d "$input" +%s ) ;;                                                         # time given
	*)   end=$(( $start + $( echo "$input" | sed "s/h/*3600+/; s/m/*60+/; s/s//; s/+$//" ) )) ;;  # duration given
esac

echo "${topic:-⏲};$end" > "$file"

while [ $( date +%s ) -lt $end ]; do dwmbar timer; sleep 0.5; done

notify-send -a timerdone -u critical "${topic:-"Timer done"}" "Started: $( date -d "@$start" +%R )"

rm "$file"; dwmbar timer
