#!/usr/bin/env sh

# `up down` | download updates (cronjob).
# `up`      | install updates.

runjob() {
    echo "running job '$*'..." >&2
    {
        "$@" >/dev/null
        echo "completed job '$*' [$?]" >&2
    } &
}

packages() {
    sudo pacman -S --noconfirm archlinux-keyring
    sudo pacman -Syyuw --noconfirm
}

nvimup() {
    nvim +PlugUpdate +PlugUpgrade +qa
}

case "$1" in
down)
    isconnected || exit 1
    polybar-msg action '#updates.send.?'
    {
        runjob packages
        runjob nvimup
        runjob qalc -e
    }
    wait
    ;;
*)
    isconnected || exit 1
    sudo pacman -Syu "$@"
    kbset
    ;;
esac

polybar-msg action '#updates.hook.0'
