#!/usr/bin/env bash

read -r -a terms <<<"$(catecho "$@")"

# If $1 is URL, just open it
echo "${terms[0]}" | grep -E '^(https?://)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]+\.[a-zA-Z0-9]+.*$' && exit

dir=~/.config/urlparse

# If has search string, check searchengines
if [ ${#terms[@]} -gt 1 ] && [ -n "${se:=$(awk '!/^#/ && $1 == "'"${terms[0]}"'" {print $2}' $dir/searchengines)}" ]; then
    printf "$se" "${terms[@]:1}"
    exit
fi

# Check bookmarks
if [ -n "${bm:=$(awk '!/^#/ && $1 == "'"${terms[0]}"'" {print $2}' $dir/bookmarks)}" ]; then
    echo "$bm"
    exit
fi

# Default to 1st search engine
se="$(awk 'NR==1 {print $2}' $dir/searchengines)"
printf "$se" "${terms[*]}"
