#!/bin/sh
# Generic URL parser, adapted from lukesmithxyz's ducksearch script.
# Reads stdin; call "urlparse dmenu" to read from dmenu instead. Prints to stdout.
# Tries to match URL, then keyword in .config/bookmarks; else return ddg search URL.

case "$1" in
	dmenu) dmenu -p "$BROWSER:" <&- ;;
	*)     cat - ;;
esac | {
	read -r url || exit 1
	echo $url | grep -E "^(http://|https://)?(www\.)?[a-zA-Z0-9-]+\.[a-zA-Z0-9-]+.*$" && exit 0
	awk '/^'"$url"' / {url=$2}; END {print url ? url : "https://duckduckgo.com/?q='"${url}"'"}' ~/.config/bookmarks
}
