#!/usr/bin/env perl
use v5.36;

chomp($_ = <STDIN>);

my $URL = "^(https?://)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]+\.[a-zA-Z0-9]+.*\$";
if (/"$URL"/) { print; exit; }

my @args = split / +/, $_;
my $key = shift @args;

my $DIR = "$ENV{HOME}/.config/urlparse";
my $find = "rg 2>/dev/null --no-filename '^$key (.*)' -r '\$1'";

if (not @args and my $url = `$find "$DIR/bookmarks" "$DIR/bookmarks.private"`) {
    print "$url";
} elsif ($url = `$find "$DIR/searchengines" "$DIR/searchengines.private"`) {
    printf "$url", (join ' ', @args);
} else {
    unshift @args, $key;
    print join(' ', @args);
}
