#!/usr/bin/env sh
# Virtual capslock that warns me with dunst.
xdotool key Caps_Lock
xset q | grep -io "Caps Lock:\s*[a-z]*" | grep -i "on" \
	&& dunstify -r 2323 -u critical -t 0 "⚠ CAPS LOCK ON! ⚠" \
	|| dunstify -r 2323 -u critical -t 10 ""

