#!/usr/bin/env sh
xdotool key Caps_Lock
if xset q | grep -i 'Caps Lock:\s*on'; then
    dunstify -r 2323 -u critical -t 0 \
        '!! CAPS LOCK !!' \
        "$(grep -B 1 'warncaps' .config/sxhkd/sxhkdrc | head -n 1)"
else
    dunstify -C 2323
fi
