#!/bin/bash
while read -r file; do
    case "$1" in
        R) convert -rotate -90 "$file" "$file" ;;
        e) notify-send sxiv "$(identify "$file" | cut -f1)" ;;
        f) convert -flop "$file" "$file" ;;
        g) launch -dx thunar "$file" ;;
        r) convert -rotate 90 "$file" "$file" ;;
        w) setbg "$file" & ;;
        y) clipimg "$file" & ;;
    esac
done
